spring:
  application:
    name: dev-productivity-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/dev_platform
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.dao: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG
    org.springframework.web: INFO